[package]
name = "lino"
version = "0.1.0"
authors = ["ahmednooor <ahmednooorr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.2"
